// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProducAPI.DBContext;

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220421135909_SeedProducts")]
    partial class SeedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProducAPI.DBContext.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SpicyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Main",
                            Description = "Aromatic golden chicken pieces in an incredible curry sauce.",
                            ImageFile = "https://freeimage.host/i/VNmlwu",
                            Name = "Butter Chicken",
                            Price = 18.0,
                            SpicyLevel = "Mild"
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Main",
                            Description = "A standard element of Goan cuisine derived from the Portuguese carne de vinha d'alhos (meat in garlic marinade).",
                            ImageFile = "https://freeimage.host/i/VNmcue",
                            Name = "Vindaloo",
                            Price = 16.0,
                            SpicyLevel = "High"
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Curry",
                            Description = "An indian lamb curry with a heady combination of intense spices in a creamy tomato curry sauce.",
                            ImageFile = "https://freeimage.host/i/VNma99",
                            Name = "Lamb Roghanjosh",
                            Price = 18.0,
                            SpicyLevel = "Medium"
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Main",
                            Description = "A rich & creamy curry made with paneer, spices, onions, tomatoes, cashews and butter.",
                            ImageFile = "https://freeimage.host/i/VNm787",
                            Name = "Paneer Butter Masala",
                            Price = 18.0,
                            SpicyLevel = "Mild"
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Dessert",
                            Description = "A madras curry is a fairly hot curry with a dark red thick sauce (the colour comes from the chillies and paprika).",
                            ImageFile = "https://freeimage.host/i/VNm0Zb",
                            Name = "Chicken Madras",
                            Price = 18.0,
                            SpicyLevel = "Mild"
                        },
                        new
                        {
                            ProductId = 6,
                            Category = "Starter",
                            Description = "A dumpling made of all-purpose flour and filled with either meat or vegetables.",
                            ImageFile = "https://freeimage.host/i/VNmEnj",
                            Name = "Nepalese Momo",
                            Price = 10.0,
                            SpicyLevel = "Medium"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
