name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./ProductAPI/ProductAPI.sln
      
    - name: Build app
      run: dotnet build ./ProductAPI/ProductAPI.sln

  docker_build_push:
      name: Publish Docker Image
      if: ${{ github.event_name == 'push' }}
      runs-on: ubuntu-latest
     # v1
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: raison1311/productservice
          always_pull: true
          build_args: arg1=value1,arg2=value2
          cache_froms: raison1311/productservice:latest
          tags: latest
